### ISSUE TITLE
No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by alangwansui** [leblanc-simon/jsOdooRpc#1]
odoo_jsonrpc.js:124 OPTIONS http://localhost/:8069/web/session/authenticate (anonymous function) @ odoo_jsonrpc.js:124internal.sendRequest @ odoo_jsonrpc.js:55exposed.login @ odoo_jsonrpc.js:156(anonymous function) @ index.html:8
index.html:1 XMLHttpRequest cannot load http://localhost/:8069/web/session/authenticate. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.
index.html:14 Error: Fail to get /web/session/authenticate(…)(anonymous function) @ index.html:14

**Comment by leblanc-simon** [comment]
it's a security protection from the browser.
You must configure your webserver to send a HTTP Header "Access-Control-Allow-Origin".

If you have an apache or nginx webserver in front of Odoo, add Header in the reverse proxy.
If your Odoo is in front, check this answer : http://stackoverflow.com/a/24011683
